spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shorturl
    username: root
    password: ghtjq2959@
    hikari:
      auto-commit: false
      maximum-pool-size: 20
      connection-timeout: 5000
      max-lifetime: 50000
      idle-timeout: 50000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: shorturl
        format_sql: true
        show_sql: false
#        default_batch_fetch_size: 1000
        use_sql_comments: false