server:
  port: 8080
  tomcat:
    threads:
      max: 200

spring:
  application:
          name: LShortUrl
  config:
    import:
      - "classpath:application-rds.yml"
      - "classpath:application-redis.yml"

logging:
  level:
    root: info
    web: info
    sql: debug
    com.zaxxer.hikari: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor: debug