spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shorturl
    username: user
    password: userpassword
    hikari:
      auto-commit: false
      maximum-pool-size: 300
      connection-timeout: 5000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: shorturl
        format_sql: true
        show_sql: false
#        default_batch_fetch_size: 1000
        use_sql_comments: false