server:
  port: 8080
  tomcat:
    threads:
      max: 500
      min-spare: 10
    accept-count: 100
    max-connections: 8192
    connection-timeout: 60000

spring:
  application:
          name: LShortUrl
  config:
    import:
      - "classpath:application-rds.yml"
      - "classpath:application-redis.yml"

logging:
  level:
    root: info
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: TRACE
#    org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl: TRACE