POST http://localhost:8083/api/v1/data/shorten
Content-Type: application/json

{
  "longUrl": "http://host.docker.internal:8088/v1/luna-short-url/home"
}

###
GET http://localhost:8083/api/v1/hGn1UITzltwRZzqEwuYPF3ZiR2Qs
Content-Type: application/json

###
GET http://localhost:8088/v1/luna-short-url/home
Content-Type: application/json