scrape_configs:
  - job_name: "celuveatdev"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 1s
    static_configs:
      - targets:
          [
            "host.docker.internal:8080",
            "host.docker.internal:8081",
            "host.docker.internal:8088",
          ]
        labels:
          application: "lshorturl"
